name: Test client changes
on:
  push:
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"

env:
  BUILD_TYPE: Release

jobs:
  test-client:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Fetch Submodules
      shell: bash
      run: |
        git submodule init
        git submodule update

    - name: Generate
      shell: bash
      run: |
        cd client
        cmake . -BBUILD

    - name: Build
      shell: bash
      run: |
        cd client
        cmake --build BUILD --config $BUILD_TYPE

